name: EasyPay Cat API Assignment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allows manual runs

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Adjust as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework Tests
      run: |
        mkdir -p reports/run_${{ github.run_number }}
        robot --output reports/run_${{ github.run_number }}/output.xml \
              --log reports/run_${{ github.run_number }}/log.html \
              --report reports/run_${{ github.run_number }}/report.html \
              Tests/

    - name: Upload Robot Framework Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports-run-${{ github.run_number }}
        path: reports/run_${{ github.run_number }}
